spring:
  main:
    web-application-type: none
    banner-mode: off
    lazy-initialization: true

logging:
  level:
    com.example.textanalyzer: DEBUG
    com.example.textanalyzer.processor: TRACE
    com.example.textanalyzer.writer: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %level - %msg%n"